[project]
name = "cs329x-a11y"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.71.0",
    "google-genai>=1.46.0",
    "openai>=2.6.1",
    "playwright>=1.55.0",
]
